const muscleExercises = {
	Trapecio: ["Trapecio", "Encogimientos de hombros (Shrugs)"],
	Trapecio_frontal: ["Trapecio", "Encogimientos de hombros (Shrugs)"],
	Esternocleidomastoideo: ["Esternocleidomastoideo", "Flexión cervical con resistencia"],
	Omohioideo: ["Omohioideo", "Retracción cervical (chin tucks)"],
	Escaleno_medio: ["Escaleno medio", "Inclinación lateral del cuello con resistencia"],
	Escaleno_anterior: ["Escaleno anterior", "Flexión lateral y rotación cervical con resistencia"],
	Escaleno_posterior: ["Escaleno posterior", "Inclinación lateral del cuello con resistencia"],
	Deltoides_anterior: ["Deltoide anterior", "Press militar"],
	Deltoides_medio: ["Deltoide medio", "Elevaciones laterales"],
	Deltoides_posterior: ["Deltoide posterior", "Face Pull"],
	Pecho_adelante: ["Pectoral", "Press de banca"],
	Serrato_anterior: ["Serrato anterior", "Push-up Plus"],
	Oblicuo_externo_adelante: ["Oblicuo externo", "Russian Twist"],
	Oblicuo_interno: ["Oblicuo externo", "Russian Twist"],
	Oblicuo_externo_espalda: ["Oblicuo externo", "Russian Twist"],
	Inscripciones_tendinosas: ["Inscripciones tendinosas", "Crunch abdominal"],
	Recto_abdominal: ["Recto abdominal", "Elevación de piernas"],
	Cabeza_larga_del_biceps_braquial: ["Cabeza larga del bíceps braquial", "Curl inclinado con mancuernas"],
	Braquial: ["Braquial", "Curl martillo"],
	Cabeza_corta_del_biceps_braquial: ["Cabeza corta del bíceps braquial", "Curl predicador"],
	Supinador: ["Supinador", "Supinación de antebrazo con mancuerna"],
	Pronador: ["Pronador", "Pronación de antebrazo con banda elástica"],
	Palmares: ["Palmares", "Flexión de muñeca"],
	Tensor_de_la_fascia_lata: ["Tensor de la fascia lata", "Abducción de cadera en polea"],
	Sartorio: ["Sartorio", "Elevación de rodilla con resistencia"],
	Recto_femoral: ["Recto femoral", "Extensión de piernas"],
	Vasto_lateral: ["Vasto lateral", "Sentadilla frontal"],
	Aductor_largo: ["Aductor largo", "Aducción de cadera en máquina"],
	Vasto_medial: ["Vasto medial", "Sentadilla con talones elevados"],
	Gastrocnemios: ["Gastrocnemios", "Elevaciones de talones de pie"],
	Soleo: ["Sóleo", "Elevaciones de talones sentado"],
	Tibial_anterior: ["Tibial anterior", "Dorsiflexión con banda elástica"],
	Extensor_largo_de_los_dedos: ["Extensor largo de los dedos", "Extensión de dedos con banda"],
	Peroneo_largo: ["Peroneo largo", "Eversión de tobillo con banda"],
	Semimembranoso: ["Semimembranoso", "Peso muerto rumano"],
	Teres_menor: ["Teres menor", "Rotación externa acostado de lado"],
	Teres_mayor: ["Teres mayor", "Jalón al pecho agarre neutro"],
	Infraspinatus: ["Infraspinatus", "Rotación externa con banda"],
	Dorsal_ancho: ["Dorsal ancho", "Dominadas"],
	Erector_de_la_columna: ["Erector de la columna", "Peso muerto"],
	Cabeza_larga_del_tricep_braquial: ["Cabeza larga del tríceps braquial", "Extensión de tríceps por encima de la cabeza"],
	Cabeza_lateral_del_triceps_braquial: ["Cabeza lateral del tríceps braquial", "Jalón de tríceps en polea"],
	Anconeo: ["Ancóneo", "Fondos en banco"],
	Braquioradial: ["Braquiorradial", "Curl martillo"],
	Extensor_de_los_dedos: ["Extensor de los dedos", "Extensión de dedos con banda"],
	Extensor_cubital_del_carpo: ["Extensor cubital del carpo", "Extensión de muñeca con mancuerna"],
	Extensor_radial_del_carpo_largo_y_corto: ["Extensor radial del carpo largo y corto", "Extensión de muñeca agarre prono"],
	Gluteo_mayor: ["Glúteo mayor", "Hip Thrust"],
	Gluteo_medio: ["Glúteo medio", "Abducción de cadera"],
	Banda_iliotibial: ["Banda iliotibial", "Caminata lateral con banda"],
	Biceps_femora: ["Bíceps femoral", "Curl femoral tumbado"],
	Semitendinoso: ["Semitendinoso", "Peso muerto rumano"],
	Aductor_mayor: ["Aductor mayor", "Sentadilla sumo"],
	Gastrocnemio: ["Gastrocnemio", "Elevaciones de talones de pie"],
	Peroneo_corto: ["Peroneo corto", "Eversión de tobillo con banda"],
	Flexor_largo_del_dedo_gordo: ["Flexor largo del dedo gordo", "Flexión plantar con énfasis en el dedo gordo"]
};

export function getMuscleExercise(muscleId) {
	return muscleExercises[muscleId] || [muscleId.replaceAll("_", " "), "Ejercicio por definir"];
}